[command]
default=ants-launch ${CONTRIB_APPS}/LCT/ancil_lct_postproc_moruses.py \
       =${source} --morphology-output ${morphology_output} -o ${output} \
       =--ants-config ${ANTS_CONFIG}

[env]
ANTS_CONFIG=${PWD}/rose-app-run.conf
output=${ANCIL_TARGET_PATH}/qrparm.veg.frac.urb2t
source=${ANCIL_TARGET_PATH}/qrparm.veg.frac.nc
morphology_output=${ANCIL_TARGET_PATH}/qrparm.MORUSES.morph

[ants_metadata]
history=${CYLC_SUITE_NAME}@${ROSE_SUITE_REVISION}:${ROSE_TASK_NAME}
