[command]
default=ants-launch ${CONTRIB_APPS}/SoilDust/ancil_soil_dust.py ${source} \
       =-o ${output} --ants-config ${ANCIL_CONFIG} \
       =--lct-ancillary ${vegfrac}

[ants_decomposition]
x_split=4
y_split=5

[env]
ANCIL_CONFIG=${PWD}/rose-app-run.conf
source=${ANCIL_TARGET_PATH}/qrparm.soil_cci
vegfrac=${ANCIL_TARGET_PATH}/qrparm.veg.frac
output=${ANCIL_TARGET_PATH}/qrparm.soil.dust

[ants_metadata]
history=${CYLC_SUITE_NAME}@${ROSE_SUITE_REVISION}:${ROSE_TASK_NAME}
