# MD: Copied from GA7 ancil suite u-ab574, to generate land/sea mask w/o lakes
#     for ocean DMS file
[env]
LANDFRACOUT=$ANCIL_TARGET_PATH/qrparm.landfrac_sea_nolakes
MASKOUT=$ANCIL_TARGET_PATH/qrparm.mask_sea_nolakes

[namelist:mask]
land_frac=1.0
larea_mask=.true.
min_lake_area=1000000.0
min_land_area=1.0
