[bunch-args]
sources=oxidants/ccmi_refc1_anqdg/clim_1988_2010/v1/ukca_oxid_clim_O3.nc
       =oxidants/ccmi_refc1_anqdg/clim_1988_2010/v1/ukca_oxid_clim_NO3.nc
       =oxidants/ccmi_refc1_anqdg/clim_1988_2010/v1/ukca_oxid_clim_HO2.nc
       =oxidants/ccmi_refc1_anqdg/clim_1988_2010/v1/ukca_oxid_clim_H2O2.nc
       =oxidants/ccmi_refc1_anqdg/clim_1988_2010/v1/ukca_oxid_clim_OH.nc
