[bunch-args]
sources=ukca_emiss/cmip5/2000/v2/ukca_emiss_BC_fossil.nc 
       =ukca_emiss/cmip5/2000/v2/ukca_emiss_OC_fossil.nc 
       =ukca_emiss/cmip5/2000/v2/ukca_emiss_BC_biofuel.nc 
       =ukca_emiss/cmip5/2000/v2/ukca_emiss_OC_biofuel.nc
       =ukca_emiss/cmip5/2000/v2/ukca_emiss_Monoterp.nc
       =ukca_emiss/gfed3.1/clim_2002_2011/v2/ukca_emiss_BC_biomass.nc 
       =ukca_emiss/gfed3.1/clim_2002_2011/v2/ukca_emiss_OC_biomass.nc
