[command]
default=true

[env]
### UG-CONTRIB
UG_CONTRIB_TRUNK=fcm:ancil_ugcontrib.xm/tags/${UG_ANTS_VERSION}

### UG-ANTS

UG_ANTS_TRUNK=fcm:ancil_ugants.xm/tags/${UG_ANTS_VERSION}

#### Links UG-CONTRIB
# From Trunk
[file:${UG_CONTRIB_APPS}/AddZerothLevel]
source=${UG_CONTRIB_TRUNK}/Apps/AddZerothLevel

#### Links UG-ANTS
[file:$ROSE_SUITE_DIR/share/fcm_make_ug_ants/build]
source=${UG_ANTS_TRUNK}
