[command]
default=ants-launch ${CONTRIB_APPS}/Lai/ancil_lai.py ${source} \
       =--relative-weights ${relative_weights} -o ${output} \
       =--ants-config ${ANCIL_CONFIG}

[ants_decomposition]
x_split=0
y_split=0

[env]
ANCIL_CONFIG=${PWD}/rose-app-run.conf
output=${ANCIL_TARGET_PATH}/lai
source=${ANCIL_MASTER}/vegetation/lai/modis_4km/v2/lai_preprocessed.nc
      =${ANCIL_TARGET_PATH}/qrparm.veg.frac.nc
relative_weights=${TRANSFORM_DIR}/lai_weights_gl9.json

[ants_metadata]
history=${CYLC_SUITE_NAME}@${ROSE_SUITE_REVISION}:${ROSE_TASK_NAME}
