[jinja2:suite.rc]
CCI_MASK=true
!!HOST_EX="exab"
KGO_TEST=false
MAKE_LFRIC=false
!!MSS_PROJECT=""
!!MSS_QUEUE=""
NCI_PROJECT=""
NCI_QUEUE="normal"
NCI_STORAGE="scratch/$PROJECT"
SITE="nci-gadi"
!!UKCA_FROM_ANTS=false
USE_ANTS=true
USE_UKCA=false
WC_URBAN=true
# Define the number of regions
nregns=1
#Define define the regions
rg01_centre=-28.5,153.5
rg01_igbp_offset=0,0
rg01_name="Lismore-tiny"
# Define the number of resolutions
rg01_nreslns=2
rg01_rot_grid=false
# Define the first outer resolution that is used by the 'driving model'
rg01_rs01_3D_ancils=true
rg01_rs01_alb_anc=true
!!rg01_rs01_arcl_dust_anc=true
!!rg01_rs01_blc=-4.0,355.11
rg01_rs01_delta=0.1,0.1
rg01_rs01_levset="L70_80km"
rg01_rs01_mask_overrides=false
rg01_rs01_min_lake_area=5000.0
rg01_rs01_moruses=true
rg01_rs01_name="era5"
rg01_rs01_npts=100,100
rg01_rs01_offset=0,0
rg01_rs01_orog_srtm=true
rg01_rs01_srtm_smooth="121"
rg01_rs01_sstsmc_anc=true
# Define the second inner resolution that is used by the
rg01_rs02_3D_ancils=true
rg01_rs02_alb_anc=true
!!rg01_rs02_arcl_dust_anc=true
!!rg01_rs02_blc=-4.0,355.11
rg01_rs02_delta=0.1,0.1
rg01_rs02_levset="L70_80km"
rg01_rs02_mask_overrides=false
rg01_rs02_min_lake_area=5000.0
rg01_rs02_moruses=true
rg01_rs02_name="d1100"
rg01_rs02_npts=50,50
rg01_rs02_offset=0,0
rg01_rs02_orog_srtm=true
rg01_rs02_srtm_smooth="121"
rg01_rs02_sstsmc_anc=true
rg01_std_model="custom"
rg01_use_centre=true
