[ants_decomposition]
x_split=0
y_split=0

[ants_metadata]
history=${CYLC_SUITE_NAME}@${ROSE_SUITE_REVISION}:${ROSE_TASK_NAME}

[command]
default=ants-launch ${CONTRIB_APPS}/CanopyHeights/ancil_canopy_heights.py ${lai} \
       =--canopy-height-factors ${canopy_height_factors} --trees-dataset ${trees} \
       =-o ${TMPDIR}/canopy_heights --ants-config ${ANCIL_CONFIG} &&
       =ants-launch ancil_2anc.py \
       =${lai} ${TMPDIR}/canopy_heights.nc -o ${output}

[env]
TMPDIR=${TMPDIR}
ANCIL_CONFIG=${PWD}/rose-app-run.conf
canopy_height_factors=${TRANSFORM_DIR}/canopy_height_factors_gl9.json
lai=${ANCIL_TARGET_PATH}/lai.nc
output=${ANCIL_TARGET_PATH}/qrparm.veg.func
trees=${ANCIL_MASTER}/vegetation/canopy/simard/v1/Simard_Pinto_3DGlobalVeg_JGR.nc
