[command]
default=true

[env]
### CONTRIB
CONTRIB_TRUNK=fcm:ancil_contrib.xm/tags/${ANTS_VERSION}

CONTRIB_BRANCH_PATH=fcm:ancil_contrib.xm/branches/dev/claudiosanchez/r18111_RAS_at_ANTS_2p1
CONTRIB_BRANCH_REV=@18601

### ANTS
ANTS_BASE_PATH=fcm:ancil_ants.xm/trunk/
ANTS_BASE_REV=@18628

#####################################
#### Links CONTRIB BRANCH
[file:${CONTRIB_APPS}/LCT]
source=${CONTRIB_BRANCH_PATH}/Apps/LCT$CONTRIB_BRANCH_REV

[file:${CONTRIB_APPS}/Orography]
source=${CONTRIB_BRANCH_PATH}/Apps/Orography$CONTRIB_BRANCH_REV

#Links CONTRIB TRUNK
[file:${CONTRIB_APPS}/CanopyHeights]
source=${CONTRIB_TRUNK}/Apps/CanopyHeights

[file:${CONTRIB_APPS}/Lai]
source=${CONTRIB_TRUNK}/Apps/Lai

[file:${CONTRIB_APPS}/SoilAlbedo]
source=${CONTRIB_TRUNK}/Apps/SoilAlbedo

[file:${CONTRIB_APPS}/SoilDust]
source=${CONTRIB_TRUNK}/Apps/SoilDust

[file:${CONTRIB_APPS}/SoilParameters]
source=${CONTRIB_TRUNK}/Apps/SoilParameters

[file:${CONTRIB_APPS}/SoilRoughness]
source=${CONTRIB_TRUNK}/Apps/SoilRoughness

[file:${CONTRIB_APPS}/SstSeaIce]
source=${CONTRIB_TRUNK}/Apps/SstSeaIce

[file:${CONTRIB_APPS}/TopographicIndex]
source=${CONTRIB_TRUNK}/Apps/TopographicIndex

#### Links ANTS
[file:$ROSE_SUITE_DIR/share/fcm_make_ants/build]
source=${ANTS_BASE_PATH}/$ANTS_BASE_REV
