[command]
default=ants-launch ${CONTRIB_APPS}/Orography/concat_srtm_tiles.py \
       =--horiz_grid "$HORIZ_GRID" --srtm_path $SRTM_PATH  \
       =--fileout $FILE_SRTM_CONCAT
       =
       =ants-launch ${CONTRIB_APPS}/Orography/ancil_orography_mean.py $FILE_SRTM_CONCAT \
       =--target-lsm ${land_binary_mask} \
       =--epsilon 0.0 \
       =--ants-config ${ANCIL_CONFIG} -o ${output}

[env]
ANCIL_CONFIG=${PWD}/rose-app-run.conf
land_binary_mask=${ANCIL_TARGET_PATH}/$TARGET_LSM
ANCIL_CONFIG=${PWD}/rose-app-run.conf
output=$ANCIL_TARGET_PATH/orog_srtm/qrparm.orog.srtm
SRTM_PATH=$ROSE_DATA/etc/srtm

[ants_regridding_horizontal]
scheme=TwoStage

[ants_decomposition]
x_split=12
y_split=12

[ants_metadata]
history=${CYLC_SUITE_NAME}@${ROSE_SUITE_REVISION}:${ROSE_TASK_NAME}
