[env]

[env=source]
description=Raw source file which is to be processed.
sort-key=env-01

[env=output]
description=Output path pre-processed file.
sort-key=env-05

[env=c4source]
sort-key=env-02

[env=transformpath]
sort-key=env-03

[env=glacierpath]
sort-key=env-04

[env=output_transform]
sort-key=env-06
