[command]
default=ants-launch ${CONTRIB_APPS}/SoilParameters/ancil_soils.py ${source} \
       =--lct-ancillary ${vegfrac} --soils-lookup ${soils_lookup} \
       =-o ${output} --ants-config ${config}

[ants_decomposition]
x_split=10
y_split=10

[env]
config=$PWD/rose-app-run.conf
output=${ANCIL_TARGET_PATH}/soil_hydrology
soils_lookup=${ANCIL_PREPROC_PATH}/soils_hydrology_lookup_clapp_hornberger.json
source=${ANCIL_PREPROC_PATH}/soils_hydrology.nc
vegfrac=${ANCIL_TARGET_PATH}/qrparm.veg.frac.nc

[ants_metadata]
history=${CYLC_SUITE_NAME}@${ROSE_SUITE_REVISION}:${ROSE_TASK_NAME}
