[command]
default=ants-launch ${CONTRIB_APPS}/TopographicIndex/ancil_topographic_index.py \
       =--ants-config ${ANTS_CONFIG} \
       =${source} --lct-ancillary ${vegfrac} -o ${output}

[ants_decomposition]
x_split=0
y_split=0

[ants_regridding_horizontal]
scheme=TwoStage

[env]
vegfrac=${ANCIL_TARGET_PATH}/qrparm.veg.frac.nc
output=${ANCIL_TARGET_PATH}/qrparm.hydtop
source=${ANCIL_PREPROC_PATH}/topographic_index.nc
ANTS_CONFIG=${PWD}/rose-app-run.conf

[ants_metadata]
history=${CYLC_SUITE_NAME}@${ROSE_SUITE_REVISION}:${ROSE_TASK_NAME}
