# Attribute modification is required as UM reconfiguration and GLOMAP updating
#  requires update_type attribute to be a character string, however the ANTS
#  ukca saver sets it to be an integer as expected by the UKCA netCDF interface.
[command]
default=ants-launch ancil_general_regrid.py --ants-config ${ANTS_CONFIG} \
       =${source} --target-grid ${target_grid} -o ${output} --save-ukca ;
       =
       =ncatted -O -h -a update_type,global,o,c,"2" ${output}

[env]
ANTS_CONFIG=${PWD}/rose-app-run.conf
target_grid=${ANCIL_TARGET_PATH}/qrparm.orog ${VERT_GRID}
output=${ANCIL_TARGET_PATH}/qrclim.aerosols.nc
source=${ANCIL_PREPROC_PATH}/aerosol_clims/glomap/gregorian/qrclim.aerosols.nc

[ants_regridding_horizontal]
scheme=TwoStage

[ants_regridding_vertical]
scheme=Linear

[ants_decomposition]
x_split=4
y_split=6

[ants_metadata]
history=${CYLC_SUITE_NAME}@${ROSE_SUITE_REVISION}:${ROSE_TASK_NAME}
