[env=target_grid]
title=Target grid filepath.

[env=output]
title=Output filepath

[env=source]
title=Source filepath

[ants_regridding_horizontal]
ns=ANTS runtime

[ants_regridding_horizontal=scheme]
compulsory=true
description=Specify the ANTS horizontal regridding scheme
help=
title=ANTS horizontal regridding scheme
ns=ANTS runtime
value-hints=Linear, TwoStage, ConservativeESMF, AreaWeighted, Nearest

[ants_decomposition]
ns=HIDDEN
[env=ANTS_CONFIG]
ns=HIDDEN
[ants_metadata]
ns=HIDDEN
