meta=ancilMask

[command]
default=ancil_igbp_wrapper

[env]
!!COASTDISTOUT=$ANCIL_TARGET_PATH/qrparm.coastdist
!!FRACTOTAL1=$ANCIL_TARGET_PATH/qrparm.total.frac1
!!FRACTOTAL2=$ANCIL_TARGET_PATH/qrparm.total.frac2
!!FRACTOTAL3=$ANCIL_TARGET_PATH/qrparm.total.frac3
IDAY_YEAR=10
IGBP_SOURCE_DATA=$ROSE_DATA/etc/ancil_master_cap/vegetation/cover/igbp/v2/qrdata.igbp
IGBP_TO_MOSES_LOOKUP=$ROSE_DATA/etc/ancil_parms/IGBP_to_MOSES/latest/IGBP_to_MOSES
!!IMASKOUT=$ANCIL_TARGET_PATH/qrparm.mask_int
IPACK=2
LANDFRACOUT=$ANCIL_TARGET_PATH/qrparm.landfrac
MASKOUT=$ANCIL_TARGET_PATH/qrparm.mask_igbp
!!MASK_CHANGES_FILE=
!!RIVER_RUNOFF_ANCILLARY=
SEARCH_RADIUS=5
SEARCH_RADIUS_COL=-1
SEARCH_RADIUS_ROW=-1
SOUTHTONORTH=1
UNIT22=$ROSE_DATA/etc/ancil_STASHmaster
VERT_LEV=$VERT_LEV
VN=9.0

[file:LOGFILE]
mode=symlink
source=(fort.7)

[!!file:fort.15]
mode=symlink
source=$MASK_CHANGES_FILE

[file:fort.38]
mode=symlink
source=$IGBP_TO_MOSES_LOOKUP

[file:fort.4]
mode=symlink
source=namectrl.nl

[!!file:fort.50]
mode=symlink
source=$RIVER_RUNOFF_ANCILLARY

[file:fort.56]
mode=symlink
source=$IGBP_SOURCE_DATA

[file:namectrl.nl]
source=$CAPGRID namelist:ancill namelist:lakes namelist:mask namelist:search namelist:vegfrac namelist:veg_polygons $VERT_LEV $CAPHORIZGRID

[namelist:ancill]
aerosol=.false.
deepst=.false.
general=.false.
lsmask=.true.
orog=.false.
ozone=.false.
smcsnow=.false.
sstice=.false.
vegfrac=.false.

[namelist:lakes]
use_lake_polygon=.false.

[namelist:mask]
diag_mask=.false.
land_frac=0.5
larea_mask=.true.
lcoast_dist=.false.
!!lcoast_dist_gc=.false.
llakes=.true.
loverride=.false.
lread_ascii_mask=.false.
lriver_run=.false.
lwrite_ascii_mask=.false.
!!max_coast_dist=400.0
min_adjacent=1
min_lake_area=$MIN_LAKE_AREA
min_lake_frac=1.0
min_land_area=0.01
w_integer=.false.
w_logical=.true.

[namelist:search]
zpole=55.0
ztropic=25.0

[namelist:veg_polygons]

[namelist:vegfrac]
frac_diag=.false.
imethod=5
offsetx=$OFFSET_X
offsety=$OFFSET_Y
