[command]
default = regrid_ancil_ct.py --output-root=${output_root} --source-root=${source_root} --destgrid-file=${destgrid_file} --calendar="gregorian" $(< ${file_list})

[env]
destgrid_file = ${ANCIL_TARGET_PATH}/${DEST_FILE}
file_list = ${FILE_LIST}
output_root = ${ANCIL_TARGET_PATH}/ukca
#source_root = ${SOURCE_ROOT}
source_root = $ROSE_DATA/etc/ancil_ukca_aero
