meta=ancilTop

[command]
default=true

[file:$ANCIL_TARGET_PATH]
mode=mkdir

[file:$ANCIL_TARGET_PATH/grid.nl]
source=namelist:grid

[file:$ANCIL_TARGET_PATH/grid_eg.nl]
source=namelist:grideg

[file:$ANCIL_TARGET_PATH/vertlevs.nl]
mode=symlink
source=$VERT_LEV

[namelist:grid]
delta_lambda_targ=$DEL_X
delta_phi_targ=$DEL_Y
global=.false.
igrid_targ=6
inwsw=1
lambda_origin_targ=$FIRST_LON
lambda_pole=$POLE_LON
phi_origin_targ=$FIRST_LAT
phi_pole=$POLE_LAT
points_lambda_targ=$NPTS_X
points_phi_targ=$NPTS_Y
rotated=$ROT_GRID

[namelist:grideg]
delta_lambda_targ=$DEL_X
delta_phi_targ=$DEL_Y
global=.false.
igrid_targ=6
inwsw=1
lambda_origin_targ=$EG_FIRST_LON
lambda_pole=$POLE_LON
phi_origin_targ=$EG_FIRST_LAT
phi_pole=$POLE_LAT
points_lambda_targ=$NPTS_X
points_phi_targ=$NPTS_Y
rotated=$ROT_GRID
zlevels=$NLEVS
