[ants_regridding_horizontal]
scheme=Linear

[ants_regridding_vertical]
scheme=Linear

[command]
default=ants-launch ancil_general_regrid.py ${source} --target-grid ${target_grid} \
       =-o ${output} --ants-config ${ANTS_CONFIG}

[env]
ANTS_CONFIG=${PWD}/rose-app-run.conf
target_grid=${HORIZ_GRID} ${VERT_GRID}
