[command]
default=ants-launch ancil_general_regrid.py --ants-config ${ANTS_CONFIG} \
       =${source} --target-lsm ${target_lsm} --invert-mask -o ${output}

[ants_regridding_horizontal]
scheme=Linear

[ants_decomposition]
y_split=0
x_split=0

[env]
ANTS_CONFIG=${PWD}/rose-app-run.conf
source=${ANCIL_MASTER}/sea_clim/GlobColour/v2/qrparm.sea.nc
target_lsm=${ANCIL_TARGET_PATH}/$TARGET_LSM
output=${ANCIL_TARGET_PATH}/qrclim.sea

[ants_metadata]
history=${CYLC_SUITE_NAME}@${ROSE_SUITE_REVISION}:${ROSE_TASK_NAME}
