[command]
default=${MODULE_SCRIPT} make -C ${SOURCE_DIRECTORY} -j ${MAKE_THREADS} ${TARGET} \
       =PROFILE=${PROFILE} \
       =RDEF_PRECISION=${RDEF_PRECISION} \
       =FIX_ENUMS=${FIX_ENUMS} \
       =VERBOSE=${VERBOSE}

[env]
FIX_ENUMS=1
PROFILE=production
RDEF_PRECISION=64
TARGET=build
VERBOSE=1

[file:$BIN_DIR]
mode=mkdir

[file:$WORKING_DIR]
mode=mkdir
