[ana:grepper.SingleCommandStatus(Comparison of SMOW)]
command=(mule_cumf.py {0} {1})
files=${DIR0}/${DATADIR}/qrclim.smow
     =${DIR1}/${DATADIR}/qrclim.smow

[ana:grepper.SingleCommandStatus(Comparison of SST)]
command=(mule_cumf.py {0} {1})
files=${DIR0}/${DATADIR}/qrclim.sst
     =${DIR1}/${DATADIR}/qrclim.sst

[ana:grepper.SingleCommandStatus(Comparison of SEA-ICE)]
command=(mule_cumf.py {0} {1})
files=${DIR0}/${DATADIR}/qrclim.seaice
     =${DIR1}/${DATADIR}/qrclim.seaice