[ana:grepper.SingleCommandStatus(Comparison of MORUSES)]
command=(mule_cumf.py {0} {1})
files=${DIR0}/${DATADIR}/qrparm.MORUSES.morph 
     =${DIR1}/${DATADIR}/qrparm.MORUSES.morph 

[ana:grepper.SingleCommandStatus(Comparison of MORUSES veg-frac)]
command=(mule_cumf.py {0} {1})
files=${DIR0}/${DATADIR}/qrparm.veg.frac.urb2t
     =${DIR1}/${DATADIR}/qrparm.veg.frac.urb2t
