#Note: Omitting dust, sulp, ocff and biom (too big!)

[ana:grepper.SingleCommandStatus(Comparison of BIOG. aero. clim.)]
command=(mule_cumf.py {0} {1})
files=${DIR0}/${DATADIR}/qrclim.biog
     =${DIR1}/${DATADIR}/qrclim.biog

[ana:grepper.SingleCommandStatus(Comparison of BLACK CARBON aero. clim.)]
command=(mule_cumf.py {0} {1})
files=${DIR0}/${DATADIR}/qrclim.blck
     =${DIR1}/${DATADIR}/qrclim.blck

[ana:grepper.SingleCommandStatus(Comparison of OZONE aero. clim.)]
command=(mule_cumf.py {0} {1})
files=${DIR0}/${DATADIR}/qrclim.ozone
     =${DIR1}/${DATADIR}/qrclim.ozone

[ana:grepper.SingleCommandStatus(Comparison of SSLT aero. clim.)]
command=(mule_cumf.py {0} {1})
files=${DIR0}/${DATADIR}/qrclim.sslt
     =${DIR1}/${DATADIR}/qrclim.sslt
