meta=ancilGeneral

[command]
default=rose mpi-launch -v central_ancillary.exe

[env]
IDAY_YEAR=10
IPACK=2
MASKIN=$ANCIL_TARGET_PATH/qrparm.mask
SEARCH_RADIUS=5
SEARCH_RADIUS_COL=-1
SEARCH_RADIUS_ROW=-1
SOUTHTONORTH=1
UNIT22=$ROSE_DATA/etc/ancil_STASHmaster
VERT_LEV=$VERT_LEV
VN=9.0

[file:LOGFILE]
mode=symlink
source=(fort.7)

[file:fort.4]
mode=symlink
source=namectrl.nl

[file:namectrl.nl]
source=$CAPGRID namelist:ancill namelist:general namelist:search $VERT_LEV $CAPHORIZGRID

[namelist:ancill]
aerosol=.false.
deepst=.false.
general=.true.
lsmask=.false.
orog=.false.
ozone=.false.
smcsnow=.false.
sstice=.false.
vegfrac=.false.

[namelist:general]
full_field=.true.
iland=1
non_type=-1.0

[namelist:search]
zpole=55.0
ztropic=25.0
