meta=ancilSstice

[command]
default=rose mpi-launch -v central_ancillary.exe

[env]
ICEIN=$ROSE_DATA/etc/ancil_master_cap/seaice/hadisst_6190/v1/qrclim.seaice
ICEOUT=$ANCIL_TARGET_PATH/qrclim.seaice
IDAY_YEAR=10
IPACK=2
MASKIN=$ANCIL_TARGET_PATH/qrparm.mask
SEARCH_RADIUS=50
SEARCH_RADIUS_COL=-1
SEARCH_RADIUS_ROW=5
SOUTHTONORTH=1
SSTIN=$ROSE_DATA/etc/ancil_master_cap/sst/hadisst_6190/v1/qrclim.sst
SSTOUT=$ANCIL_TARGET_PATH/qrclim.sst
UNIT22=$ROSE_DATA/etc/ancil_STASHmaster
VERT_LEV=$VERT_LEV
VN=9.0

[file:LOGFILE]
mode=symlink
source=(fort.7)

[file:fort.4]
mode=symlink
source=namectrl.nl

[file:namectrl.nl]
source=$CAPGRID namelist:ancill namelist:sstice namelist:search $VERT_LEV $CAPHORIZGRID

[namelist:ancill]
aerosol=.false.
deepst=.false.
general=.false.
lsmask=.false.
orog=.false.
ozone=.false.
smcsnow=.false.
sstice=.true.
vegfrac=.false.

[namelist:search]
zpole=55.0
ztropic=25.0

[namelist:sstice]
conc_value=0.1
crit_conc=0.1
lake_climatology=.false.
lfrac_ice=.true.
licedpt=.false.
long_climatology=.false.
sst_ice_match=.true.
