mode=rose_bunch

[ants_regridding_horizontal]
scheme=Linear

[ants_regridding_vertical]
scheme=Linear

[bunch]
command-format=ants-launch ancil_general_regrid.py ${source_root}/%(sources)s \
              =--target-grid ${target_grid} --save-ukca \
              =-o ${output_root}/%(sources)s --ants-config ${ANTS_CONFIG}
pool-size=1

[env]
ANTS_CONFIG=${PWD}/rose-app-run.conf
target_grid=${HORIZ_GRID} ${VERT_GRID}
output_root = ${ANCIL_TARGET_PATH}/ukca
source_root = ${ANCIL_MASTER}

[file:${ANCIL_TARGET_PATH}/ukca]
mode=mkdir

