[namelist:mesh]
n_meshes=4
mesh_maps='dynamics:multigrid_l1','multigrid_l1:multigrid_l2','multigrid_l2:multigrid_l3'
mesh_names='dynamics','multigrid_l1','multigrid_l2','multigrid_l3'

[namelist:planar_mesh]
edge_cells_x=$NPTS_X,$NPTS_X_ON_2,$NPTS_X_ON_4,$NPTS_X_ON_8
edge_cells_y=$NPTS_Y,$NPTS_Y_ON_2,$NPTS_Y_ON_4,$NPTS_Y_ON_8
