[command]
default=python ${CYLC_SUITE_DEF_PATH}/app/${ROSE_TASK_APP}/bin/archive.py
[env]
ROOTDIR=${ANCIL_TARGET_PATH}
MASSROOTDIR=moose:adhoc/users/${MOO_ID}/ancils/${CYLC_SUITE_NAME}_${REGN}_${RESN}
