[command]
default=ants-launch ${CONTRIB_APPS}/LCT/ancil_lct.py ${source} \ 
       = --target-lsm  $target_lsm --transform-path ${transformpath} \
       =  -o ${output_vegfrac} \
       = --ants-config ${ANTS_CONFIG}

[env]
target_lsm=${TARGET_LSM}
output_vegfrac=${OUTPUT_VEGFRAC}
