[ants_decomposition]
x_split=5
y_split=5

[ants_metadata]
history=${CYLC_SUITE_NAME}@${ROSE_SUITE_REVISION}:${ROSE_TASK_NAME}

[env]
ANCIL_CONFIG=${PWD}/rose-app-run.conf
TARGET_LSM=$ANCIL_TARGET_PATH/$TARGET_LSM