mode=rose_bunch

[bunch]
command-format=ants-launch ${CONTRIB_APPS}/Orography/ancil_orography_mean.py $FILE_SRTM_CONCAT \
              =--target-lsm ${land_binary_mask} \
              =--epsilon %(epsilon)s \
              =--ants-config ${ANCIL_CONFIG} -o ${OUTPUT}.%(epsilon)s

pool-size=1

[env]
SOURCE=${ANCIL_TARGET_PATH}/orog_srtm/qrparm.orog.srtm
OUTPUT=${ANCIL_TARGET_PATH}/orog_srtm/qrparm.orog.srtm.raymond

[bunch-args]
epsilon=1 2 8 32 128 512 2048
