[command]
default=ants-launch ${CONTRIB_APPS}/LCT/ancil_lct.py ${source} \ 
       = --target-grid ${target_grid} --transform-path ${transformpath} \
       = -o ${output_vegfrac} --landseamask-output ${output_lsm}        \
       = --ants-config ${ANTS_CONFIG}

[ants_decomposition]
x_split=20
y_split=20

[env]
source=${ANCIL_MASTER}/vegetation/cover/cci/v3/vegetation_fraction.nc
transformpath=${TRANSFORM_DIR}/cci2jules_ra1.json
output_vegfrac=${ANCIL_TARGET_PATH}/qrparm.veg.frac_cci_pre_c4
output_lsm=${ANCIL_TARGET_PATH}
target_grid=${HORIZ_GRID}
ANTS_CONFIG=${PWD}/rose-app-run.conf
