[jinja2:suite.rc]
CCI_MASK=true
KGO_TEST=false
SITE="niwa-cray-cs500"
USE_ANTS=true
nregns=2

rg01_igbp_offset=0,0
rg01_name="NZCSM"
rg01_nreslns=1
rg01_pole=49.55,171.77
rg01_rot_grid=true
rg01_rs01_3D_ancils=true
rg01_rs01_alb_anc=false
rg01_rs01_blc=-8.50675,172.49325
#rg01_rs01_blc=-8.5,172.5
rg01_rs01_delta=0.0135,0.0135
rg01_rs01_levset="L90_40km"
rg01_rs01_mask_overrides=false
rg01_rs01_min_lake_area=5000.0
rg01_rs01_moruses=false
rg01_rs01_name="1p5K"
rg01_rs01_npts=01200,01350
rg01_rs01_orog_srtm=true
rg01_rs01_srtm_smooth="121"
rg01_rs01_sstsmc_anc=false
rg01_std_model="custom"
rg01_use_centre=false

rg02_centre=-36.8309,174.7455
rg02_igbp_offset=0,0
rg02_name="AKL"
rg02_nreslns=2
rg02_rot_grid=false

rg02_rs01_3D_ancils=true
rg02_rs01_alb_anc=false
rg02_rs01_delta=0.003,0.003
rg02_rs01_levset="L140_40km"
rg02_rs01_mask_overrides=false
rg02_rs01_min_lake_area=5000.0
rg02_rs01_moruses=true
rg02_rs01_name="AKL300"
rg02_rs01_npts=300,300
rg02_rs01_offset=0,0
rg02_rs01_orog_srtm=true
rg02_rs01_srtm_smooth="121"
rg02_rs01_sstsmc_anc=false

rg02_rs02_3D_ancils=true
rg02_rs02_alb_anc=false
rg02_rs02_delta=0.0135,0.0135
rg02_rs02_levset="L140_40km"
rg02_rs02_mask_overrides=false
rg02_rs02_min_lake_area=5000.0
rg02_rs02_moruses=true
rg02_rs02_name="AKL1p5K"
rg02_rs02_npts=300,300
rg02_rs02_offset=0,0
rg02_rs02_orog_srtm=true
rg02_rs02_srtm_smooth="121"
rg02_rs02_sstsmc_anc=false

rg02_std_model="custom"
rg02_use_centre=true

