[jinja2:suite.rc]
KGO_TEST=true
KGO_TEST_NAME="SH"
SITE="moex-cray"
HOST_EX="exab"
USE_UKCA=false
nregns=2
rg01_centre=-38,178
rg01_name="NORTHNZ"
rg01_rot_grid=true
rg01_rs01_3D_ancils=false
rg01_rs01_alb_anc=true
rg01_rs01_arcl_dust_anc=false
rg01_rs01_delta=0.04,0.04
rg01_rs01_name="km4p4"
rg02_centre=-54,-69.5
rg02_igbp_offset=0,0
rg02_name="PATAGONIA"
rg02_nreslns=1
rg02_rot_grid=true
rg02_rs01_3D_ancils=false
rg02_rs01_alb_anc=true
rg02_rs01_arcl_dust_anc=false
rg02_rs01_delta=0.02,0.02
rg02_rs01_levset="L90_40km"
rg02_rs01_mask_overrides=false
rg02_rs01_min_lake_area=5000.0
rg02_rs01_moruses=true
rg02_rs01_name="km2p2"
rg02_rs01_npts=200,200
rg02_rs01_offset=0,0
rg02_rs01_orog_srtm=true
rg02_rs01_srtm_smooth="121"
rg02_rs01_sstsmc_anc=false
rg02_std_model="custom"
rg02_use_centre=true
