[jinja2:suite.rc]
SITE="moex-cray"
HOST_EX="exab"
KGO_TEST=true
KGO_TEST_NAME="def_mover"
USE_UKCA=false
rg01_rs01_3D_ancils=false
rg01_rs01_arcl_dust_anc=false
rg01_rs01_mask_overrides=true
rg01_rs01_mask_overrides_file="/data/users/rmed_workflows/KGOs/inputs/mask_overrides/edited_mask_test.txt"
rg01_rs01_moruses=false
rg01_rs01_orog_srtm=false
!!rg01_rs01_srtm_smooth="121"
