[jinja2:suite.rc]
SITE="moex-cray"
HOST_EX="exab"
KGO_TEST=true
KGO_TEST_NAME="def_UKV"
USE_UKCA=false
!!rg01_centre=50.7,-3.5
!!rg01_rot_grid=false
rg01_rs01_3D_ancils=false
rg01_rs01_alb_anc=true
rg01_rs01_arcl_dust_anc=true
!!rg01_rs01_delta=0.0135,0.0135
rg01_rs01_grid_path="/common/internal/umdir/ancil/data/namelist/grids/grid.ukv_new/v1/grid.ukv_new"
!!rg01_rs01_npts=200,200
!!rg01_rs01_offset=0,0
rg01_rs01_orog_srtm=false
!!rg01_rs01_srtm_smooth="121"
rg01_rs01_sstsmc_anc=true
rg01_rs01_vargrid="variable"
rg01_rs01_vargrid_path="/common/internal/umdir/ancil/data/namelist/variable_grids/variable.ukv_new/v1/variable.ukv_new"
rg01_std_model="predefined"
!!rg01_use_centre=true
