[jinja2:suite.rc]
ARCHIVE_ANCILS=false
HOST_EX="exab"
KGO_TEST=true
KGO_TEST_NAME="Paris"
SITE="moex-cray"
USE_UKCA=false
WC_URBAN=true
rg01_centre=48.86,2.35
rg01_name="Paris"
rg01_nreslns=2
rg01_rot_grid=true
rg01_rs01_3D_ancils=false
rg01_rs01_arcl_dust_anc=false
rg01_rs01_delta=0.003,0.003
rg01_rs01_levset="L70_40km"
rg01_rs01_name="km0p3"
rg01_rs02_3D_ancils=true
rg01_rs02_alb_anc=false
rg01_rs02_delta=0.02,0.02
rg01_rs02_levset="L90_40km"
rg01_rs02_mask_overrides=false
rg01_rs02_min_lake_area=5000.0
rg01_rs02_moruses=true
rg01_rs02_name="km2p2"
rg01_rs02_npts=200,200
rg01_rs02_offset=0,0
rg01_rs02_orog_srtm=true
rg01_rs02_srtm_smooth="121"
rg01_rs02_sstsmc_anc=false
