[jinja2:suite.rc]
ARCHIVE_ANCILS=false
HOST_EX="exab"
KGO_TEST=true
KGO_TEST_NAME="UK_LFRIC"
MAKE_LFRIC=true
SITE="moex-cray"
USE_UKCA=false
!!rg01_centre=50.7,-3.5
rg01_name="UK"
rg01_pole=37.5,177.5
rg01_rot_grid=true
!!rg01_rs01_arcl_dust_anc=false
rg01_rs01_blc=-2.9764,353.8332
rg01_rs01_delta=0.0147, 0.0139
rg01_rs01_levset="L70_40km"
rg01_rs01_moruses=false
rg01_rs01_name="1km"
rg01_rs01_npts=672,672
!!rg01_rs01_offset=0,0
rg01_rs01_sstsmc_anc=true
rg01_use_centre=false
