# Override for running tests at NCI
# For normal use set SITE="nci-gadi" inside `rose edit`

[jinja2:suite.rc]
SITE="nci-gadi"
MAKE_LFRIC=true
NCI_PROJECT=""
NCI_QUEUE="normal"
NCI_STORAGE=""
rg01_name="DAR"
rg01_pole=90.0,180.0
rg01_centre=-12.43325,130.84675
rg01_rs01_npts=480,480
rg01_rs01_delta=0.0135,0.0135
rg01_rs01_levset="L70_40km"
rg01_rs01_sstsmc_anc=true
