[jinja2:suite.rc]
HOST_EX="exab"
KGO_TEST=true
KGO_TEST_NAME="def_custom_blc"
SITE="moex-cray"
USE_UKCA=false
!!rg01_centre=50.7,-3.5
rg01_rs01_3D_ancils=false
rg01_rs01_arcl_dust_anc=true
rg01_rs01_blc=49.34325,355.14325
!!rg01_rs01_offset=0,0
rg01_use_centre=false
