meta=mesh_tools/rose-meta/lfric-mesh_tools/HEAD

[command]
default=${MODULE_SCRIPT} mpiexec -n 1 planar_mesh_generator mesh_generation.nml

[env]
mesh_generator=Planar

[file:$ROSE_DATA/meshes]
mode=mkdir

[file:$DESTINATION_DIRECTORY]
mode=mkdir

[file:mesh_generation.nml]
mode=auto
source=namelist:mesh
      = (namelist:partitions)
      = (namelist:planar_mesh)
      = (namelist:rotation)

[namelist:mesh]
coord_sys='ll'
geometry='spherical'
mesh_file_prefix='${OUTPUT_FILE_PREFIX}'
mesh_names='dynamics'
n_meshes=1
partition_mesh=.false.
rotate_mesh=$ROTATED
topology='non_periodic'

[namelist:partitions]
n_partitions=0

[namelist:planar_mesh]
create_lbc_mesh=.false.
apply_stretch_transform=.false.
domain_size=$LEN_X,$LEN_Y
edge_cells_x=$NPTS_X
edge_cells_y=$NPTS_Y
domain_centre=$CENTRE_LON,$CENTRE_LAT
periodic_x=.false.
periodic_y=.false.

[namelist:rotation]
rotation_target='north_pole'
target_north_pole=$POLE_LON,$POLE_LAT
