[command]
default=ants-launch ancil_general_regrid.py --ants-config ${ANTS_CONFIG} \
       =${source} --target-grid ${target_grid} -o ${output}

[ants_regridding_horizontal]
scheme=Linear

[ants_decomposition]
y_split=0
x_split=0

[env]
ANTS_CONFIG=${PWD}/rose-app-run.conf
source=${ANCIL_MASTER}/lake/ARClake/v2/qrdata.mask.nc
target_grid=${HORIZ_GRID}
output=${ANCIL_TARGET_PATH}/qrparm.lake

[ants_metadata]
history=${CYLC_SUITE_NAME}@${ROSE_SUITE_REVISION}:${ROSE_TASK_NAME}
