[env]

[env=source]
description=Vegetation file from the ancil_lct task.
           =Note: using the .nc avoids errors in WC_URBAN for KGOs
	   =with the CAP land-sea mask. Latitudes in the CAP land-sea
           =mask and vegetation files are slightly different if the
           =.nc is not used.
sort-key=env-01

[env=source_WC]
description=WorldCover source file.
sort-key=env-02

[env=target_lsm]
description=Land sea mask to be used.
sort-key=env-03

[env=output]
description=Output file.
sort-key=env-04

[env=nonurb_subgrid_frac]
description=This parameter represents the fraction of WorldCover
           =urban fraction which is estimated to be non-urban sub-grid.
           =It is used to downweight the WorldCover urban fractions.
           =Default value is zero. Reasoning: in the 10 m WorldCover
           =dataset, grid cells are assigned a land cover class. Grid 
           =cells classified as urban are assumed to be 100% urban in
           =the source file. However, often there will be sub-grid 
           =non-urban e.g., trees or back gardens.
sort-key=env-05

[env=ANTS_CONFIG]
sort-key=env-06

