[command]
default=ug-ants-launch ${UG_CONTRIB_APPS}/AddZerothLevel/ancil_add_zeroth_level.py ${source} ${output}

[env]
source=${ANCIL_FILENAME_PATH}.ugrid.nc
output=${ANCIL_FILENAME_PATH}_L${NLEVS}_O${NLEVS}.ugrid.nc
