[ants_decomposition]
x_split=5
y_split=5

[ants_metadata]
history=${CYLC_SUITE_NAME}@${ROSE_SUITE_REVISION}:${ROSE_TASK_NAME}

[command]
default=ants-launch ${CONTRIB_APPS}/LCT/ancil_lct_postproc_wc_urban.py \
       =--ants-config ${ANTS_CONFIG} ${source} ${source_WC} \
       =--target-lsm ${target_lsm} --output ${output} \
       =--nonurb-subgrid-frac ${nonurb_subgrid_frac}

[env]
ANTS_CONFIG=${PWD}/rose-app-run.conf
nonurb_subgrid_frac=0.0
source=${ANCIL_TARGET_PATH}/${TARGET_VEGFRAC}_pre_c4.nc
target_lsm=${ANCIL_TARGET_PATH}/${TARGET_LSM}.nc
output=${ANCIL_TARGET_PATH}/${TARGET_VEGFRAC}_pre_c4
source_WC=${ANCIL_PREPROC_PATH}/urban_fraction.nc
