[file:$ROSE_DATA/etc/srtm]
mode=symlink
source=/data/users/rmed_workflows/ancil_sources/SRTM/SRTM3vn2.1/0p5deg_tiles/pp

[file:$ROSE_DATA/etc/ants_preproc]
# location of preprocessed vegfrac and lsm netcdf files for ANTS
mode=symlink
source=/data/users/rmed_workflows/ancil_sources/preproc_files

# Soure of ancils for ANTS
[file:$ROSE_DATA/etc/ancil_master_ants]
mode=symlink
source=/data/exab//common/internal/ancildir/master

# source to compute the horizon data for the LFRIC orography ancillary
[file:$ROSE_DATA/etc/socrates]
source=fcm:socrates.xm/trunk

[file:$ROSE_SUITE_DIR/share/fcm_make_cap]
mode=symlink
source=/home/users/adam.maycock/cylc-run/r5766_ex1a_changes_exab/share/fcm_make/build/bin

