[file:$ROSE_DATA/etc/tidl]
mode=symlink
source=/usr/local/bin/tidl

[file:$ROSE_DATA/etc/srtm]
mode=symlink
source=/project/wind_renewables/SRTM/0p5deg_tiles/pp

[file:$ROSE_DATA/etc/ite]
mode=symlink
source=/data/cr2/hadsw/ITE

[file:$ROSE_DATA/etc/ants_preproc]
# location of preprocessed vegfrac and lsm netcdf files for ANTS
mode=symlink
source=/data/users/hadzc/RMED/ANTS/preproc/

# Soure of ancils for ANTS
[file:$ROSE_DATA/etc/ancil_master_ants]
mode=symlink
source=/hpc/projects/um1/ancil/atmos/master

# source to compute the horizon data for the LFRIC orography ancillary
[file:$ROSE_DATA/etc/socrates]
source=fcm:socrates.xm/trunk
