[file:$ROSE_DATA/etc/srtm]
mode=symlink
source=/g/data/access/projects/access/data/SRTM/pp

[file:$ROSE_DATA/etc/ants_preproc]
# location of preprocessed vegfrac and lsm netcdf files for ANTS
mode=symlink
source=$TIDS/RMED/ANTS/preproc

# Soure of ancils for ANTS
[file:$ROSE_DATA/etc/ancil_master_ants]
mode=symlink
source=$TIDS/UM/ancil/atmos/master

# source to compute the horizon data for the LFRIC orography ancillary
[file:$ROSE_DATA/etc/socrates]
source=fcm:socrates.xm_tr
