[file:$ROSE_DATA/etc/srtm]
mode=symlink
source=$UMDIR/srtm/pp

[file:$ROSE_DATA/etc/ants_preproc]
# location of preprocessed vegfrac and lsm netcdf files for ANTS
mode=symlink
source=$UMDIR/RMED/ANTS/preproc

# Soure of ancils for ANTS
[file:$ROSE_DATA/etc/ancil_master_ants]
mode=symlink
source=$UMDIR/ancil/atmos/master
