[file:$ROSE_DATA/etc/um_STASHmaster]
mode=symlink
source=$UMDIR/vn${UM_VN}/ctldata/STASHmaster

[file:$ROSE_DATA/etc/ancil_STASHmaster]
mode=symlink
source=$UMDIR/vn${CAP_VN}/ctldata/STASHmaster

# Source ancils CAP
[file:$ROSE_DATA/etc/ancil_master_cap]
mode=symlink
source=$UMDIR/ancil/atmos/master

[file:$ROSE_DATA/etc/ancil_parms]
mode=symlink
source=$UMDIR/ancil/data/parameters

[file:$ROSE_SUITE_DIR/share/fcm_make_cap]
mode=symlink
source=/home/users/adam.maycock/cylc-run/r5766_ex1a_changes_exab/share/fcm_make/build/bin

#
# This is the full path to the directory containing the netcdf ukca ancillary data for
# offline oxidants and emmissions. The standard setup uses CMIP5 emissions.
#
[file:$ROSE_DATA/etc/ancil_ukca_aero]
mode=symlink
source=/data/users/anthony.jones/ancil/n216e_mon_gcal/ncdf_ukca