[file:$ROSE_DATA/etc/um_STASHmaster]
mode=symlink
source=$UMDIR/vn${UM_VN}/ctldata/STASHmaster

[file:$ROSE_DATA/etc/ancil_STASHmaster]
mode=symlink
source=$UMDIR/vn${CAP_VN}/ctldata/STASHmaster

#
# This is the full path to the directory containing the L90 aerosol ancillaries.
#
[file:$ROSE_DATA/etc/ancil_master_aero_L90_cap]
mode=symlink
source=/scratch/$USER/RMED/RA2/L90_AEROSOLS

# Source ancils CAP
[file:$ROSE_DATA/etc/ancil_master_cap]
mode=symlink
source=$UMDIR/ancil/atmos/master

[file:$ROSE_DATA/etc/ancil_parms]
mode=symlink
source=$UMDIR/ancil/data/parameters

#
# This is the full path to the directory containing the netcdf ukca ancillary data for
# offline oxidants and emmissions. The standard setup uses CMIP5 emissions.
#
[file:$ROSE_DATA/etc/ancil_ukca_aero]
mode=symlink
source=/dev/null
#source=/scratch/$USER/data/access/ngm/data/ras/ncdf_ukca

[file:$ROSE_DATA/etc/ancil_ukca_glm1]
mode=symlink
source=/dev/null
# /data/d05/frfp/hamgo_ancils/ukca-v10p3/n216e_mon_gcal/ncdf_ukca

[file:$ROSE_DATA/etc/ancil_ukca_glm2]
mode=symlink
source=/dev/null
#source=$UMDIR/ancil/atmos/n216e/
