[command]
default=ants-launch ${CONTRIB_APPS}/SoilRoughness/ancil_soil_roughness.py \
       =--target-lsm ${target_lsm} \
       =--leaf-area-index ${target_lai} \
       =--target-vegfrac ${target_vegfrac} \
       =--output ${output} \
       = ${source}

[ants_decomposition]
x_split=0
y_split=0

[env]
ANCIL_CONFIG=${PWD}/rose-app-run.conf
source=${ANCIL_MASTER}/soil_roughness/prigent12/v1/soil_roughness_preproc_prigent12.nc
target_lai=${ANCIL_MASTER}/vegetation/lai/modis_4km/v2/lai_preprocessed.nc
target_lsm=${ANCIL_TARGET_PATH}/${TARGET_LSM}
target_vegfrac=${ANCIL_TARGET_PATH}/qrparm.veg.frac.nc
output=${ANCIL_TARGET_PATH}/qrparm.soil_roughness


[ants_metadata]
history=${CYLC_SUITE_NAME}@${ROSE_SUITE_REVISION}:${ROSE_TASK_NAME}
