[command]
default=ants-launch ${CONTRIB_APPS}/SoilAlbedo/ancil_soil_albedo.py ${source} \
       =-o ${TMPDIR}/soil_albedo --ants-config ${ANCIL_CONFIG} \
       =--lct-ancillary ${vegfrac} && \
       =
       =# Append soil albedo to the soil parameter ancillary
       =ants-launch ${CYLC_SUITE_DEF_PATH}/app/ancil_soil_albedo/bin/append.py \
       =${soil_hydrology} ${TMPDIR}/soil_albedo -o ${output}

[ants_decomposition]
x_split=4
y_split=5

[env]
ANCIL_CONFIG=${PWD}/rose-app-run.conf
source=${ANCIL_MASTER}/soil_albedo/classic/v3/soil_albedo.nc
soil_hydrology=${ANCIL_TARGET_PATH}/soil_hydrology
output=${ANCIL_TARGET_PATH}/qrparm.soil_cci
vegfrac=${ANCIL_TARGET_PATH}/qrparm.veg.frac.nc

[ants_metadata]
history=${CYLC_SUITE_NAME}@${ROSE_SUITE_REVISION}:${ROSE_TASK_NAME}
