[env]
# ANCIL FILES
[ana:grepper.SingleCommandStatus(Comparison of LSM)]
command=(mule_cumf.py {0} {1})
files=${DIR0}/${DATADIR}/qrparm.mask
     =${DIR1}/${DATADIR}/qrparm.mask
[ana:grepper.SingleCommandStatus(Comparison of VEG-FRAC)]
command=(mule_cumf.py {0} {1})
files=${DIR0}/${DATADIR}/qrparm.veg.frac
     =${DIR1}/${DATADIR}/qrparm.veg.frac

[ana:grepper.SingleCommandStatus(Comparison of VEG-FUNC)]
command=(mule_cumf.py {0} {1})
files=${DIR0}/${DATADIR}/qrparm.veg.func
     =${DIR1}/${DATADIR}/qrparm.veg.func

[ana:grepper.SingleCommandStatus(Comparison of SOIL)]
command=(mule_cumf.py {0} {1})
files=${DIR0}/${DATADIR}/qrparm.soil_cci
     =${DIR1}/${DATADIR}/qrparm.soil_cci

[ana:grepper.SingleCommandStatus(Comparison of orog)]
command=(mule_cumf.py {0} {1})
files=${DIR0}/${DATADIR}/qrparm.orog
     =${DIR1}/${DATADIR}/qrparm.orog

[ana:grepper.SingleCommandStatus(Comparison of mean-orog)]
command=(mule_cumf.py {0} {1})
files=${DIR0}/${DATADIR}/qrparm.orog.mn
     =${DIR1}/${DATADIR}/qrparm.orog.mn

[ana:grepper.SingleCommandStatus(Comparison of Topographic-index)]
command=(mule_cumf.py {0} {1})
files=${DIR0}/${DATADIR}/qrparm.hydtop 
     =${DIR1}/${DATADIR}/qrparm.hydtop 

[ana:grepper.SingleCommandStatus(Comparison of lakes)]
command=(mule_cumf.py {0} {1})
files=${DIR0}/${DATADIR}/qrparm.lake
     =${DIR1}/${DATADIR}/qrparm.lake

[ana:grepper.SingleCommandStatus(Comparison of Chlorophyll)]
command=(mule_cumf.py {0} {1})
files=${DIR0}/${DATADIR}/qrclim.sea
     =${DIR1}/${DATADIR}/qrclim.sea
